features:
  - vote_count
  - popularity
  - run_time
  - Horror
  - War
  - History
  - Dimension Films
  - Dune Entertainment
  - Screen Gems
  - United Artists
  - Film4 Productions

target: vote_average

raw_path: data/raw/top_1000_popular_movies_tmdb.csv
clean_path: data/clean/movies.csv
